-- Create profiles table (integrates with Supabase Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  role text default 'member', -- 'admin' or 'member'
  avatar text default '👤',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create incomes table
create table public.incomes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  source text not null,
  amount numeric not null,
  is_variable boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create expenses table
create table public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  amount numeric not null,
  category text,
  due_date date,
  responsible_id uuid references public.profiles(id) on delete set null,
  is_recur_ring boolean default false,
  recurrence_type text default 'fixed', -- 'fixed' or 'variable'
  status text default 'pending', -- 'pending' or 'paid'
  is_auto_debit boolean default false,
  payment_url text,
  bill_arrival_day integer
);

-- Create cards table
create table public.cards (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  last4 text,
  cutoff_date integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create loans table
create table public.loans (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  type text,
  custom_name text,
  entity_name text,
  total_value numeric,
  monthly_payment numeric,
  term integer,
  rate numeric,
  rate_type text,
  is_auto_debit boolean default false,
  disbursement_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.incomes enable row level security;
alter table public.expenses enable row level security;
alter table public.cards enable row level security;
alter table public.loans enable row level security;

-- Create Policies (Simple policies for a family app: everyone can read/write everything if authenticated)
-- PROFILES
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);

-- INCOMES
create policy "Authenticated users can select incomes" on public.incomes for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert incomes" on public.incomes for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update incomes" on public.incomes for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete incomes" on public.incomes for delete using (auth.role() = 'authenticated');

-- EXPENSES
create policy "Authenticated users can select expenses" on public.expenses for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert expenses" on public.expenses for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update expenses" on public.expenses for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete expenses" on public.expenses for delete using (auth.role() = 'authenticated');

-- CARDS
create policy "Authenticated users can select cards" on public.cards for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert cards" on public.cards for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update cards" on public.cards for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete cards" on public.cards for delete using (auth.role() = 'authenticated');

-- LOANS
create policy "Authenticated users can select loans" on public.loans for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert loans" on public.loans for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update loans" on public.loans for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete loans" on public.loans for delete using (auth.role() = 'authenticated');

-- TRIGGER FOR NEW USER
-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role, avatar)
  values (new.id, new.email, new.raw_user_meta_data->>'name', 'admin', '👤');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
